# frps xtcp coordinator example
bindPort = 7000

auth.method = "token"
auth.token = "12345678"

log.to = "console"
log.level = "info"

transport.tls.force = false
natholeAnalysisDataReserveHours = 168
